clear 
clc

% simulation_name = 'RUN33_6_NEWEDES_HAM';
sim_name = 'RUN33_6_NEWEDES';

% data path 
data_path = '../Data';

%% load data

load([data_path '/' sim_name '_Ecosystem.mat'])
load([data_path '/' sim_name '_Physics.mat'])

clear data_path sim_name

Lat = EcosystemData.Y;
Lon = linspace(0,360,numel(EcosystemData.X));

%%

f5 = figure(5);
f5.Position = [74 379 1213 891];
clf

t = tiledlayout(3,2, 'TileSpacing','compact', ...
                     'Padding','compact', ...
                     'TileIndexing', 'columnmajor');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ax{1} = nexttile;
axh = axesm('MapProjection','mollweid',...
                'plinelocation',90,...
                'mlinelocation',Inf,...
                'MapLatLimit',[-80 80],...
                'MapLonLimit',[1 359]+130,...
                'Frame', 'on',...
                'Grid', 'off');
pcolorm(Lat,Lon,log10(EcosystemData.TSi.Annual)')
colormap(ax{1},parula)
caxis([0 4])
ch = colorbar;
ch.Ticks = 0:4;
ch.TickLabels = {'1','10','100','1000','10000'};
box off
landareas = shaperead('landareas.shp','UseGeoCoords',true);
geoshow(landareas,...
        'FaceColor',[0.75 0.75 0.75],...
        'EdgeColor','k',...
        'LineWidth',0.5);
title('(a) Total Si (mmol m^{-2})')
set(gcf,'Color','w')
axis off
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ax{2} = nexttile;
axh = axesm('MapProjection','mollweid',...
                'plinelocation',90,...
                'mlinelocation',Inf,...
                'MapLatLimit',[-80 80],...
                'MapLonLimit',[1 359]+130,...
                'Frame', 'on',...
                'Grid', 'off');
pcolorm(Lat,Lon,log10(EcosystemData.TN.Annual)')
colormap(ax{2},parula)
caxis([0 4])
ch = colorbar;
ch.Ticks = 0:4;
ch.TickLabels = {'1','10','100','1000','10000'};
box off
landareas = shaperead('landareas.shp','UseGeoCoords',true);
geoshow(landareas,...
        'FaceColor',[0.75 0.75 0.75],...
        'EdgeColor','k',...
        'LineWidth',0.5);
title('(b) Total N (mmol m^{-2})')
set(gcf,'Color','w')
axis off
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ax{3} = nexttile;
axh = axesm('MapProjection','mollweid',...
                'plinelocation',90,...
                'mlinelocation',Inf,...
                'MapLatLimit',[-80 80],...
                'MapLonLimit',[1 359]+130,...
                'Frame', 'on',...
                'Grid', 'off');
pcolorm(Lat,Lon,log10(EcosystemData.TFe.Annual)')
colormap(ax{3},parula)
caxis([-3 -1])
ch = colorbar;
ch.Ticks = -3:-1;
ch.TickLabels = {'0.001','0.01','0.1'};
box off
landareas = shaperead('landareas.shp','UseGeoCoords',true);
geoshow(landareas,...
        'FaceColor',[0.75 0.75 0.75],...
        'EdgeColor','k',...
        'LineWidth',0.5);
title('(c) Total Fe (mmol m^{-2})')
set(gcf,'Color','w')
axis off
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ax{4} = nexttile;
axh = axesm('MapProjection','mollweid',...
                'plinelocation',90,...
                'mlinelocation',Inf,...
                'MapLatLimit',[-80 80],...
                'MapLonLimit',[1 359]+130,...
                'Frame', 'on',...
                'Grid', 'off');

phiSiN = EcosystemData.TSi.Annual./EcosystemData.TN.Annual ./ 3;
pcolorm(Lat,Lon,log10(phiSiN)')
colormap(ax{4},redblue)
caxis([-2 2])
ch = colorbar;
ch.Ticks = -2:2;
ch.TickLabels = {'\div100','\div10','\theta_{Si:N}=3','\times10','\times100'};
box off
landareas = shaperead('landareas.shp','UseGeoCoords',true);
geoshow(landareas,...
        'FaceColor',[0.75 0.75 0.75],...
        'EdgeColor','k',...
        'LineWidth',0.5);
title('(d) Normalised Si:N supply ratio')
set(gcf,'Color','w')
axis off
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ax{5} = nexttile;
axh = axesm('MapProjection','mollweid',...
                'plinelocation',90,...
                'mlinelocation',Inf,...
                'MapLatLimit',[-80 80],...
                'MapLonLimit',[1 359]+130,...
                'Frame', 'on',...
                'Grid', 'off');

phiSiFe = EcosystemData.TSi.Annual./EcosystemData.TFe.Annual ./ 48000;
pcolorm(Lat,Lon,log10(phiSiFe)')
colormap(ax{5},redblue)
caxis([-2 2])
ch = colorbar;
ch.Ticks = -2:2;
ch.TickLabels = {'\div100','\div10','\theta_{Si:Fe}=48000','\times10','\times100'};
box off
landareas = shaperead('landareas.shp','UseGeoCoords',true);
geoshow(landareas,...
        'FaceColor',[0.75 0.75 0.75],...
        'EdgeColor','k',...
        'LineWidth',0.5);
title('(e) Normalised Si:Fe supply ratio')
set(gcf,'Color','w')
axis off
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ax{6} = nexttile;
axh = axesm('MapProjection','mollweid',...
                'plinelocation',90,...
                'mlinelocation',Inf,...
                'MapLatLimit',[-80 80],...
                'MapLonLimit',[1 359]+130,...
                'Frame', 'on',...
                'Grid', 'off');

phiNFe = EcosystemData.TN.Annual./EcosystemData.TFe.Annual ./ 16000;
pcolorm(Lat,Lon,log10(phiNFe)')
colormap(ax{6},redblue)
caxis([-2 2])
ch = colorbar;
ch.Ticks = -2:2;
ch.TickLabels = {'\div100','\div10','\theta_{N:Fe}=16000','\times10','\times100'};
box off
landareas = shaperead('landareas.shp','UseGeoCoords',true);
geoshow(landareas,...
        'FaceColor',[0.75 0.75 0.75],...
        'EdgeColor','k',...
        'LineWidth',0.5);
title('(f) Normalised N:Fe supply ratio')
set(gcf,'Color','w')
axis off
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

set(findall(gcf,'-property','FontSize'),'FontSize',14)

exportgraphics(gcf,['../Figures/Figure_5.png'],'Resolution',600)

